const departments = [
    { id: 1, name: "AUDITORIA INTERNA" },
    { id: 2, name: "CONSULTORIA JURIDICA" },
    { id: 3, name: "DIRECCION GENERAL" },
    { id: 4, name: "GERENCIA DE ATENCION INTEGRAL Y PREVENCION DE LA VIOLENCIA CONTRA LAS MUJERES" },
    { id: 5, name: "GERENCIA DE DESARROLLO ALTERNATIVO Y POLITICA REGIONAL" },
    { id: 6, name: "GERENCIA DE INVESTIGACION Y CAPACITACION" },
    { id: 7, name: "GERENCIA DE LA DEFENSORIA NACIONAL DE LOS DERECHOS DE LA MUJER" },
    { id: 8, name: "OFICINA DE ADMINISTRACION Y SERVICIOS" },
    { id: 9, name: "OFICINA DE ATENCION A LA CIUDADANIA" },
    { id: 10, name: "OFICINA DE COMUNICACION E IMAGEN INSTITUCIONAL" },
    { id: 11, name: "OFICINA DE PLANIFICACION ORGANIZACION Y PRESUPUESTO" },
    { id: 12, name: "OFICINA DE RECURSOS HUMANOS" },
    { id: 13, name: "OFICINA DE RELACIONES INTERNACIONALES" },
    { id: 14, name: "OFICINA DE SISTEMAS Y TECNOLOGIA DE LA INFORMACION" }
  ];

  export default departments;